### DEV SITE
#BASE_URL_DEV="http://next-room-cicd-env.eba-duriufh6.ap-southeast-2.elasticbeanstalk.com/marketing"
##ACCESS_TOKEN_DEV="key_dev_1"
#
#
## STAGING Site
##BASE_URL_STAGING="https://staging.fatherofapps.com"
##ACCESS_TOKEN_STAGING=""
#
#BASE_URL_STAGING="http://next-room-cicd-env.eba-duriufh6.ap-southeast-2.elasticbeanstalk.com/marketing"
##ACCESS_TOKEN_STAGING=""
#
#
### LIVE SITE
#BASE_URL_LIVE="http://next-room-cicd-env.eba-duriufh6.ap-southeast-2.elasticbeanstalk.com/marketing"
##ACCESS_TOKEN_LIVE=""

# product
BASE_URL_DEV="http://10.0.2.2:8083/marketing/"
BASE_URL_STAGING="http://62.72.30.111:8083/marketing/"
BASE_URL_LIVE="http://10.0.2.2:8083/marketing/"

# url user
URL_USER_DEV="http://10.0.2.2:8080/user/"
URL_USER_STAGING="http://62.72.30.111:8081/user/"
URL_USER_LIVE="http://10.0.2.2:8080/user/"
# url chat realtime API
URL_CHAT_DEV="http://10.0.2.2:8082/chat/ws"
URL_CHAT_STAGING="http://10.0.2.2:8082/chat/ws"
URL_CHAT_LIVE="http://10.0.2.2:8082/chat/ws"

# api payment
PAYMENT_DEV = "http://10.0.2.2:8084/payment/"
PAYMENT_STAGING = "http://62.72.30.111:8085/payment/"
PAYMENT_LIVE ="http://10.0.2.2:8084/payment/"