### DEV SITE
#BASE_URL_DEV="http://next-room-cicd-env.eba-duriufh6.ap-southeast-2.elasticbeanstalk.com/marketing"
##ACCESS_TOKEN_DEV="key_dev_1"
#
#
## STAGING Site
##BASE_URL_STAGING="https://staging.fatherofapps.com"
##ACCESS_TOKEN_STAGING=""
#
#BASE_URL_STAGING="http://next-room-cicd-env.eba-duriufh6.ap-southeast-2.elasticbeanstalk.com/marketing"
##ACCESS_TOKEN_STAGING=""
#
#
### LIVE SITE
#BASE_URL_LIVE="http://next-room-cicd-env.eba-duriufh6.ap-southeast-2.elasticbeanstalk.com/marketing"
##ACCESS_TOKEN_LIVE=""

# product
BASE_URL_DEV="http://ec2-54-206-187-225.ap-southeast-2.compute.amazonaws.com:8080/marketing/"
BASE_URL_STAGING="http://ec2-54-206-187-225.ap-southeast-2.compute.amazonaws.com:8080/marketing/"
BASE_URL_LIVE="http://ec2-54-206-187-225.ap-southeast-2.compute.amazonaws.com:8080/marketing/"

# url user
URL_USER_DEV="http://ec2-3-25-80-181.ap-southeast-2.compute.amazonaws.com:8080/user/"
URL_USER_STAGING="http://ec2-3-25-80-181.ap-southeast-2.compute.amazonaws.com:8080/user/"
URL_USER_LIVE="http://ec2-3-25-80-181.ap-southeast-2.compute.amazonaws.com:8080/user/"
# url chat realtime API
URL_CHAT_DEV="http://ec2-3-107-147-137.ap-southeast-2.compute.amazonaws.com:8080/ws"
URL_CHAT_STAGING="http://ec2-3-107-147-137.ap-southeast-2.compute.amazonaws.com:8080/ws"
URL_CHAT_LIVE="http://ec2-3-107-147-137.ap-southeast-2.compute.amazonaws.com:8080/ws"